api:
  provider:
    intune:
      base-uri: http://localhost:8088
      endpoint: /api/v1/intune/verify
server:
  port: 8680

azure:
  activedirectory:
#    client-id: cd163353-08c0-4cba-9299-58635fc1867e
#    client-secret: KQ27Q~iuOowznMaRvwsIRuyczajp3DUcdw7U6
    client-id: 2f01c547-7798-433d-a2b2-1970f6c4cd0a
    client-secret: Vb18Q~W~woX30xXp9tA6SXgAdXbNVZemJCuaZcyd
    tenant-id: a42e43e2-c7b8-499c-89a6-4b9bac2d5a6e
    authorization-clients:
      graph:
        scopes: https://graph.microsoft.com/User.Read
      testco-webapp:
        scopes:
          - api://testco-webapp/Consumer.read
          - openid
          - profile
          - offline_access
      testco-fe:
        scopes: 
          - openid
          - profile
          - api://testco-fe2/File.Scan
          - offline_access
#          - api://testco-webapp/Consumer.read