#server:
#  error:
#    path: /error
#    whitelabel:
#      enabled: false
spring:
  autoconfigure:
    exclude: org.springframework.boot.autoconfigure.web.ErrorMvcAutoConfiguration
  profiles:
    active: testco

logging:
  level:
    org:
      springframework:
        security: TRACE
    com:
      azure:
        spring: TRACE